default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: fortune_development

test:
  <<: *default
  database: fortune_test

production:
  <<: *default
  database: fortune_production
